version: "3.8"
services:
  dev:
    build:
      context: .
      dockerfile: deploy/Dockerfile.dev
  qa:
    build:
      context: .
      dockerfile: deploy/Dockerfile.qa

  prod:
    build:
      context: .
      dockerfile: deploy/Dockerfile.prod
