# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main","qa", "dev" ]
  pull_request:
    branches: [ "main","qa", "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
  deploy-dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'branch' && github.ref== 'refs/heads/dev'
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
            echo "Deploying to dev environment..."
            # Your deploy command for dev
            
  deploy-qa:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'branch' && github.ref== 'refs/heads/qa'
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Deploy qa
        run: |
            echo "Deploying to qa environment..."
            # Your deploy command for qa
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'branch' && github.ref== 'refs/heads/main'
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
            echo "Deploying to production environment..."
            # Your deploy command for main
